name: Continuous Integration / Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- pnpm + cache ----------
      - uses: pnpm/action-setup@v4
        with:
          version: 8        # Specify pnpm version (adjust to your preferred version)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # stable Node versions
    steps:
      - uses: actions/checkout@v4

      # -------- pnpm + cache ----------
      - uses: pnpm/action-setup@v4
        with:
          version: 8        # Specify pnpm version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- pnpm + cache ----------
      - uses: pnpm/action-setup@v4
        with:
          version: 8        # Specify pnpm version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run test 