name: Release

on:
  workflow_dispatch:           # manual trigger
  push:
    branches: [master]   # assumes your main branch is master

concurrency:
  group: release               # never run two releases in parallel
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # needed for pushing version commits & creating releases 
      issues: write            # needed for commenting on issues
      pull-requests: write     # needed for commenting on PRs
      id-token: write          # needed for npm provenance

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # semantic-release needs full history & tags
          persist-credentials: false  # use GitHub token with correct permissions

      # -------- pnpm + node (same cache strategy used in CI) ----
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          provenance: true

      - run: pnpm install --frozen-lockfile

      # (optional) run tests / build again for extra safety
      - run: pnpm run test
      - run: pnpm run build

      # -------- install semantic-release and plugins --------
      - name: Install semantic-release
        run: pnpm add -D semantic-release @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits

      # -------- run release --------
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npx semantic-release 