name: PR Semantics

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pull-request
        with:
          sha: ${{ github.head_ref }}

      - name: Add Commit Lint
        if: ${{ steps.pull-request.outputs.pr_found == 'true' }}
        run: |
          npm init -y
          npm install --save-dev @commitlint/cli @commitlint/config-angular
          echo "module.exports = { \
            extends: ['@commitlint/config-angular'], \
            rules: { \
              'subject-empty': [2, 'never'], \
              'scope-empty'  : [2, 'never'], \
              'type-case'    : [2, 'always', 'lower-case'], \
              'type-empty'   : [2, 'never'], \
              'type-enum'    : [2, 'always', ['chore','feat','fix','refactor']], \
              'scope-enum'   : [2, 'always', ['openapi']] \
            } \
          };" > commitlint.config.js

      - name: Validate Semantic Title
        if: ${{ steps.pull-request.outputs.pr_found == 'true' }}
        run: |
          echo "${{ steps.pull-request.outputs.pr_title }}" | npx commitlint

      - name: Get Semantic Commit Scope
        if: ${{ steps.pull-request.outputs.pr_found == 'true' }}
        id: scope
        run: |
          echo "name=$(echo '${{ steps.pull-request.outputs.pr_title }}' | cut -d'(' -f1)" >> $GITHUB_OUTPUT 