name: Pull Request Semantics

on:
  pull_request:
    branches:
      - master

jobs:
  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Validate PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Validating PR title: $PR_TITLE"
          
          # Install commitlint
          npm init -y
          npm install --save-dev @commitlint/cli @commitlint/config-angular
          
          # Configure commitlint
          echo "module.exports = { \
            extends: ['@commitlint/config-angular'], \
            rules: { \
              'subject-empty': [2, 'never'], \
              'scope-empty': [0, 'never'], \
              'type-case': [2, 'always', 'lower-case'], \
              'type-empty': [2, 'never'], \
              'type-enum': [2, 'always', ['chore','feat','fix','refactor']] \
            } \
          };" > commitlint.config.js
          
          # Validate title
          echo "$PR_TITLE" | npx commitlint
